// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc 33.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `stream.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:fx.ipc.proto.Stream)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Stream {
    // special fields
    // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Stream {
    fn default() -> &'a Stream {
        <Stream as ::protobuf::Message>::default_instance()
    }
}

impl Stream {
    pub fn new() -> Stream {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Stream {
    const NAME: &'static str = "Stream";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Stream {
        Stream::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Stream {
        static instance: Stream = Stream {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `Stream`
pub mod stream {
    // @@protoc_insertion_point(message:fx.ipc.proto.Stream.StreamStats)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct StreamStats {
        // message fields
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamStats.progress)
        pub progress: f32,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamStats.connections)
        pub connections: u64,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamStats.download_speed)
        pub download_speed: u32,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamStats.upload_speed)
        pub upload_speed: u32,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamStats.downloaded)
        pub downloaded: u64,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamStats.total_size)
        pub total_size: u64,
        // special fields
        // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.StreamStats.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a StreamStats {
        fn default() -> &'a StreamStats {
            <StreamStats as ::protobuf::Message>::default_instance()
        }
    }

    impl StreamStats {
        pub fn new() -> StreamStats {
            ::std::default::Default::default()
        }
    }

    impl ::protobuf::Message for StreamStats {
        const NAME: &'static str = "StreamStats";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    13 => {
                        self.progress = is.read_float()?;
                    },
                    16 => {
                        self.connections = is.read_uint64()?;
                    },
                    24 => {
                        self.download_speed = is.read_uint32()?;
                    },
                    32 => {
                        self.upload_speed = is.read_uint32()?;
                    },
                    40 => {
                        self.downloaded = is.read_uint64()?;
                    },
                    48 => {
                        self.total_size = is.read_uint64()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if self.progress != 0. {
                my_size += 1 + 4;
            }
            if self.connections != 0 {
                my_size += ::protobuf::rt::uint64_size(2, self.connections);
            }
            if self.download_speed != 0 {
                my_size += ::protobuf::rt::uint32_size(3, self.download_speed);
            }
            if self.upload_speed != 0 {
                my_size += ::protobuf::rt::uint32_size(4, self.upload_speed);
            }
            if self.downloaded != 0 {
                my_size += ::protobuf::rt::uint64_size(5, self.downloaded);
            }
            if self.total_size != 0 {
                my_size += ::protobuf::rt::uint64_size(6, self.total_size);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if self.progress != 0. {
                os.write_float(1, self.progress)?;
            }
            if self.connections != 0 {
                os.write_uint64(2, self.connections)?;
            }
            if self.download_speed != 0 {
                os.write_uint32(3, self.download_speed)?;
            }
            if self.upload_speed != 0 {
                os.write_uint32(4, self.upload_speed)?;
            }
            if self.downloaded != 0 {
                os.write_uint64(5, self.downloaded)?;
            }
            if self.total_size != 0 {
                os.write_uint64(6, self.total_size)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> StreamStats {
            StreamStats::new()
        }

        fn clear(&mut self) {
            self.progress = 0.;
            self.connections = 0;
            self.download_speed = 0;
            self.upload_speed = 0;
            self.downloaded = 0;
            self.total_size = 0;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static StreamStats {
            static instance: StreamStats = StreamStats {
                progress: 0.,
                connections: 0,
                download_speed: 0,
                upload_speed: 0,
                downloaded: 0,
                total_size: 0,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    // @@protoc_insertion_point(message:fx.ipc.proto.Stream.StreamEvent)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct StreamEvent {
        // message fields
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamEvent.type)
        pub type_: ::protobuf::EnumOrUnknown<stream_event::Type>,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamEvent.filename)
        pub filename: ::std::string::String,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamEvent.state)
        pub state: ::std::option::Option<::protobuf::EnumOrUnknown<StreamState>>,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.StreamEvent.stats)
        pub stats: ::protobuf::MessageField<StreamStats>,
        // special fields
        // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.StreamEvent.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a StreamEvent {
        fn default() -> &'a StreamEvent {
            <StreamEvent as ::protobuf::Message>::default_instance()
        }
    }

    impl StreamEvent {
        pub fn new() -> StreamEvent {
            ::std::default::Default::default()
        }
    }

    impl ::protobuf::Message for StreamEvent {
        const NAME: &'static str = "StreamEvent";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.type_ = is.read_enum_or_unknown()?;
                    },
                    18 => {
                        self.filename = is.read_string()?;
                    },
                    24 => {
                        self.state = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                    },
                    34 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.stats)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if self.type_ != ::protobuf::EnumOrUnknown::new(stream_event::Type::STATE_CHANGED) {
                my_size += ::protobuf::rt::int32_size(1, self.type_.value());
            }
            if !self.filename.is_empty() {
                my_size += ::protobuf::rt::string_size(2, &self.filename);
            }
            if let Some(v) = self.state {
                my_size += ::protobuf::rt::int32_size(3, v.value());
            }
            if let Some(v) = self.stats.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if self.type_ != ::protobuf::EnumOrUnknown::new(stream_event::Type::STATE_CHANGED) {
                os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
            }
            if !self.filename.is_empty() {
                os.write_string(2, &self.filename)?;
            }
            if let Some(v) = self.state {
                os.write_enum(3, ::protobuf::EnumOrUnknown::value(&v))?;
            }
            if let Some(v) = self.stats.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> StreamEvent {
            StreamEvent::new()
        }

        fn clear(&mut self) {
            self.type_ = ::protobuf::EnumOrUnknown::new(stream_event::Type::STATE_CHANGED);
            self.filename.clear();
            self.state = ::std::option::Option::None;
            self.stats.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static StreamEvent {
            static instance: StreamEvent = StreamEvent {
                type_: ::protobuf::EnumOrUnknown::from_i32(0),
                filename: ::std::string::String::new(),
                state: ::std::option::Option::None,
                stats: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `StreamEvent`
    pub mod stream_event {
        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:fx.ipc.proto.Stream.StreamEvent.Type)
        pub enum Type {
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.StreamEvent.Type.STATE_CHANGED)
            STATE_CHANGED = 0,
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.StreamEvent.Type.STATS_CHANGED)
            STATS_CHANGED = 1,
        }

        impl ::protobuf::Enum for Type {
            const NAME: &'static str = "Type";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<Type> {
                match value {
                    0 => ::std::option::Option::Some(Type::STATE_CHANGED),
                    1 => ::std::option::Option::Some(Type::STATS_CHANGED),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<Type> {
                match str {
                    "STATE_CHANGED" => ::std::option::Option::Some(Type::STATE_CHANGED),
                    "STATS_CHANGED" => ::std::option::Option::Some(Type::STATS_CHANGED),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [Type] = &[
                Type::STATE_CHANGED,
                Type::STATS_CHANGED,
            ];
        }

        impl ::std::default::Default for Type {
            fn default() -> Self {
                Type::STATE_CHANGED
            }
        }

    }

    // @@protoc_insertion_point(message:fx.ipc.proto.Stream.Error)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Error {
        // message fields
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.type)
        pub type_: ::protobuf::EnumOrUnknown<error::Type>,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.already_exists)
        pub already_exists: ::protobuf::MessageField<error::AlreadyExists>,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.not_found)
        pub not_found: ::protobuf::MessageField<error::NotFound>,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.io)
        pub io: ::protobuf::MessageField<error::IoError>,
        // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.parse)
        pub parse: ::protobuf::MessageField<error::ParseError>,
        // special fields
        // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.Error.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Error {
        fn default() -> &'a Error {
            <Error as ::protobuf::Message>::default_instance()
        }
    }

    impl Error {
        pub fn new() -> Error {
            ::std::default::Default::default()
        }
    }

    impl ::protobuf::Message for Error {
        const NAME: &'static str = "Error";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    8 => {
                        self.type_ = is.read_enum_or_unknown()?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.already_exists)?;
                    },
                    26 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.not_found)?;
                    },
                    34 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.io)?;
                    },
                    42 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.parse)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if self.type_ != ::protobuf::EnumOrUnknown::new(error::Type::ALREADY_EXISTS) {
                my_size += ::protobuf::rt::int32_size(1, self.type_.value());
            }
            if let Some(v) = self.already_exists.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.not_found.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.io.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.parse.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if self.type_ != ::protobuf::EnumOrUnknown::new(error::Type::ALREADY_EXISTS) {
                os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
            }
            if let Some(v) = self.already_exists.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            if let Some(v) = self.not_found.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
            }
            if let Some(v) = self.io.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
            }
            if let Some(v) = self.parse.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Error {
            Error::new()
        }

        fn clear(&mut self) {
            self.type_ = ::protobuf::EnumOrUnknown::new(error::Type::ALREADY_EXISTS);
            self.already_exists.clear();
            self.not_found.clear();
            self.io.clear();
            self.parse.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Error {
            static instance: Error = Error {
                type_: ::protobuf::EnumOrUnknown::from_i32(0),
                already_exists: ::protobuf::MessageField::none(),
                not_found: ::protobuf::MessageField::none(),
                io: ::protobuf::MessageField::none(),
                parse: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    /// Nested message and enums of message `Error`
    pub mod error {
        // @@protoc_insertion_point(message:fx.ipc.proto.Stream.Error.AlreadyExists)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct AlreadyExists {
            // message fields
            // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.AlreadyExists.message)
            pub message: ::std::string::String,
            // special fields
            // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.Error.AlreadyExists.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a AlreadyExists {
            fn default() -> &'a AlreadyExists {
                <AlreadyExists as ::protobuf::Message>::default_instance()
            }
        }

        impl AlreadyExists {
            pub fn new() -> AlreadyExists {
                ::std::default::Default::default()
            }
        }

        impl ::protobuf::Message for AlreadyExists {
            const NAME: &'static str = "AlreadyExists";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            self.message = is.read_string()?;
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if !self.message.is_empty() {
                    my_size += ::protobuf::rt::string_size(1, &self.message);
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if !self.message.is_empty() {
                    os.write_string(1, &self.message)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> AlreadyExists {
                AlreadyExists::new()
            }

            fn clear(&mut self) {
                self.message.clear();
                self.special_fields.clear();
            }

            fn default_instance() -> &'static AlreadyExists {
                static instance: AlreadyExists = AlreadyExists {
                    message: ::std::string::String::new(),
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }

        // @@protoc_insertion_point(message:fx.ipc.proto.Stream.Error.NotFound)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct NotFound {
            // message fields
            // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.NotFound.message)
            pub message: ::std::string::String,
            // special fields
            // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.Error.NotFound.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a NotFound {
            fn default() -> &'a NotFound {
                <NotFound as ::protobuf::Message>::default_instance()
            }
        }

        impl NotFound {
            pub fn new() -> NotFound {
                ::std::default::Default::default()
            }
        }

        impl ::protobuf::Message for NotFound {
            const NAME: &'static str = "NotFound";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            self.message = is.read_string()?;
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if !self.message.is_empty() {
                    my_size += ::protobuf::rt::string_size(1, &self.message);
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if !self.message.is_empty() {
                    os.write_string(1, &self.message)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> NotFound {
                NotFound::new()
            }

            fn clear(&mut self) {
                self.message.clear();
                self.special_fields.clear();
            }

            fn default_instance() -> &'static NotFound {
                static instance: NotFound = NotFound {
                    message: ::std::string::String::new(),
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }

        // @@protoc_insertion_point(message:fx.ipc.proto.Stream.Error.IoError)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct IoError {
            // message fields
            // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.IoError.message)
            pub message: ::std::string::String,
            // special fields
            // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.Error.IoError.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a IoError {
            fn default() -> &'a IoError {
                <IoError as ::protobuf::Message>::default_instance()
            }
        }

        impl IoError {
            pub fn new() -> IoError {
                ::std::default::Default::default()
            }
        }

        impl ::protobuf::Message for IoError {
            const NAME: &'static str = "IoError";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            self.message = is.read_string()?;
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if !self.message.is_empty() {
                    my_size += ::protobuf::rt::string_size(1, &self.message);
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if !self.message.is_empty() {
                    os.write_string(1, &self.message)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> IoError {
                IoError::new()
            }

            fn clear(&mut self) {
                self.message.clear();
                self.special_fields.clear();
            }

            fn default_instance() -> &'static IoError {
                static instance: IoError = IoError {
                    message: ::std::string::String::new(),
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }

        // @@protoc_insertion_point(message:fx.ipc.proto.Stream.Error.ParseError)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct ParseError {
            // message fields
            // @@protoc_insertion_point(field:fx.ipc.proto.Stream.Error.ParseError.message)
            pub message: ::std::string::String,
            // special fields
            // @@protoc_insertion_point(special_field:fx.ipc.proto.Stream.Error.ParseError.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a ParseError {
            fn default() -> &'a ParseError {
                <ParseError as ::protobuf::Message>::default_instance()
            }
        }

        impl ParseError {
            pub fn new() -> ParseError {
                ::std::default::Default::default()
            }
        }

        impl ::protobuf::Message for ParseError {
            const NAME: &'static str = "ParseError";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            self.message = is.read_string()?;
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if !self.message.is_empty() {
                    my_size += ::protobuf::rt::string_size(1, &self.message);
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if !self.message.is_empty() {
                    os.write_string(1, &self.message)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> ParseError {
                ParseError::new()
            }

            fn clear(&mut self) {
                self.message.clear();
                self.special_fields.clear();
            }

            fn default_instance() -> &'static ParseError {
                static instance: ParseError = ParseError {
                    message: ::std::string::String::new(),
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }

        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:fx.ipc.proto.Stream.Error.Type)
        pub enum Type {
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.Error.Type.ALREADY_EXISTS)
            ALREADY_EXISTS = 0,
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.Error.Type.NOT_FOUND)
            NOT_FOUND = 1,
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.Error.Type.INVALID_STATE)
            INVALID_STATE = 2,
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.Error.Type.INVALID_RANGE)
            INVALID_RANGE = 3,
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.Error.Type.PARSE)
            PARSE = 4,
            // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.Error.Type.IO)
            IO = 5,
        }

        impl ::protobuf::Enum for Type {
            const NAME: &'static str = "Type";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<Type> {
                match value {
                    0 => ::std::option::Option::Some(Type::ALREADY_EXISTS),
                    1 => ::std::option::Option::Some(Type::NOT_FOUND),
                    2 => ::std::option::Option::Some(Type::INVALID_STATE),
                    3 => ::std::option::Option::Some(Type::INVALID_RANGE),
                    4 => ::std::option::Option::Some(Type::PARSE),
                    5 => ::std::option::Option::Some(Type::IO),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<Type> {
                match str {
                    "ALREADY_EXISTS" => ::std::option::Option::Some(Type::ALREADY_EXISTS),
                    "NOT_FOUND" => ::std::option::Option::Some(Type::NOT_FOUND),
                    "INVALID_STATE" => ::std::option::Option::Some(Type::INVALID_STATE),
                    "INVALID_RANGE" => ::std::option::Option::Some(Type::INVALID_RANGE),
                    "PARSE" => ::std::option::Option::Some(Type::PARSE),
                    "IO" => ::std::option::Option::Some(Type::IO),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [Type] = &[
                Type::ALREADY_EXISTS,
                Type::NOT_FOUND,
                Type::INVALID_STATE,
                Type::INVALID_RANGE,
                Type::PARSE,
                Type::IO,
            ];
        }

        impl ::std::default::Default for Type {
            fn default() -> Self {
                Type::ALREADY_EXISTS
            }
        }

    }

    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:fx.ipc.proto.Stream.StreamState)
    pub enum StreamState {
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.StreamState.PREPARING)
        PREPARING = 0,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.StreamState.STREAMING)
        STREAMING = 1,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Stream.StreamState.STOPPED)
        STOPPED = 2,
    }

    impl ::protobuf::Enum for StreamState {
        const NAME: &'static str = "StreamState";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<StreamState> {
            match value {
                0 => ::std::option::Option::Some(StreamState::PREPARING),
                1 => ::std::option::Option::Some(StreamState::STREAMING),
                2 => ::std::option::Option::Some(StreamState::STOPPED),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<StreamState> {
            match str {
                "PREPARING" => ::std::option::Option::Some(StreamState::PREPARING),
                "STREAMING" => ::std::option::Option::Some(StreamState::STREAMING),
                "STOPPED" => ::std::option::Option::Some(StreamState::STOPPED),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [StreamState] = &[
            StreamState::PREPARING,
            StreamState::STREAMING,
            StreamState::STOPPED,
        ];
    }

    impl ::std::default::Default for StreamState {
        fn default() -> Self {
            StreamState::PREPARING
        }
    }

}

// @@protoc_insertion_point(message:fx.ipc.proto.ServerStream)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ServerStream {
    // message fields
    // @@protoc_insertion_point(field:fx.ipc.proto.ServerStream.url)
    pub url: ::std::string::String,
    // @@protoc_insertion_point(field:fx.ipc.proto.ServerStream.filename)
    pub filename: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:fx.ipc.proto.ServerStream.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ServerStream {
    fn default() -> &'a ServerStream {
        <ServerStream as ::protobuf::Message>::default_instance()
    }
}

impl ServerStream {
    pub fn new() -> ServerStream {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for ServerStream {
    const NAME: &'static str = "ServerStream";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.url = is.read_string()?;
                },
                18 => {
                    self.filename = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.url.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.url);
        }
        if !self.filename.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.filename);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.url.is_empty() {
            os.write_string(1, &self.url)?;
        }
        if !self.filename.is_empty() {
            os.write_string(2, &self.filename)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ServerStream {
        ServerStream::new()
    }

    fn clear(&mut self) {
        self.url.clear();
        self.filename.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ServerStream {
        static instance: ServerStream = ServerStream {
            url: ::std::string::String::new(),
            filename: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

// @@protoc_insertion_point(message:fx.ipc.proto.StreamStateRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StreamStateRequest {
    // message fields
    // @@protoc_insertion_point(field:fx.ipc.proto.StreamStateRequest.filename)
    pub filename: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:fx.ipc.proto.StreamStateRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StreamStateRequest {
    fn default() -> &'a StreamStateRequest {
        <StreamStateRequest as ::protobuf::Message>::default_instance()
    }
}

impl StreamStateRequest {
    pub fn new() -> StreamStateRequest {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for StreamStateRequest {
    const NAME: &'static str = "StreamStateRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.filename = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.filename.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filename);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.filename.is_empty() {
            os.write_string(1, &self.filename)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StreamStateRequest {
        StreamStateRequest::new()
    }

    fn clear(&mut self) {
        self.filename.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StreamStateRequest {
        static instance: StreamStateRequest = StreamStateRequest {
            filename: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

// @@protoc_insertion_point(message:fx.ipc.proto.StreamStateResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StreamStateResponse {
    // message fields
    // @@protoc_insertion_point(field:fx.ipc.proto.StreamStateResponse.result)
    pub result: ::protobuf::EnumOrUnknown<super::message::response::Result>,
    // @@protoc_insertion_point(field:fx.ipc.proto.StreamStateResponse.state)
    pub state: ::std::option::Option<::protobuf::EnumOrUnknown<stream::StreamState>>,
    // @@protoc_insertion_point(field:fx.ipc.proto.StreamStateResponse.error)
    pub error: ::protobuf::MessageField<stream::Error>,
    // special fields
    // @@protoc_insertion_point(special_field:fx.ipc.proto.StreamStateResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StreamStateResponse {
    fn default() -> &'a StreamStateResponse {
        <StreamStateResponse as ::protobuf::Message>::default_instance()
    }
}

impl StreamStateResponse {
    pub fn new() -> StreamStateResponse {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for StreamStateResponse {
    const NAME: &'static str = "StreamStateResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.result = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.state = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.error)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.result != ::protobuf::EnumOrUnknown::new(super::message::response::Result::OK) {
            my_size += ::protobuf::rt::int32_size(1, self.result.value());
        }
        if let Some(v) = self.state {
            my_size += ::protobuf::rt::int32_size(2, v.value());
        }
        if let Some(v) = self.error.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.result != ::protobuf::EnumOrUnknown::new(super::message::response::Result::OK) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.result))?;
        }
        if let Some(v) = self.state {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.error.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StreamStateResponse {
        StreamStateResponse::new()
    }

    fn clear(&mut self) {
        self.result = ::protobuf::EnumOrUnknown::new(super::message::response::Result::OK);
        self.state = ::std::option::Option::None;
        self.error.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StreamStateResponse {
        static instance: StreamStateResponse = StreamStateResponse {
            result: ::protobuf::EnumOrUnknown::from_i32(0),
            state: ::std::option::Option::None,
            error: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}
