spring:
  application:
    name: Popcorn Time
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  tomcat:
    min-spare-threads: 1
    connection-timeout: -1
  port: 8091

logging:
  level:
    org.springframework: WARN
    com.github.yoep.popcorn: INFO
  file:
    name: '${log.dir}/logs/popcorn-time.log'
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 25MB
      total-size-cap: 100MB

popcorn:
  providers:
    movies:
      uris:
        - https://movies-v2.api-fetch.sh
        - https://movies-v2.api-fetch.am
        - https://movies-v2.api-fetch.website
        - https://popcorn-ru.tk
      genres:
        - all
        - action
        - adventure
        - animation
        - comedy
        - crime
        - disaster
        - documentary
        - drama
        - family
        - fantasy
        - history
        - holiday
        - horror
        - music
        - mystery
        - romance
        - science-fiction
        - short
        - suspense
        - thriller
        - war
        - western
      sort-by:
        - trending
        - popularity
        - last added
        - year
        - title
        - rating
    series:
      uris:
        - https://tv-v2.api-fetch.sh
        - https://tv-v2.api-fetch.am
        - https://tv-v2.api-fetch.website
        - https://popcorn-ru.tk
      genres:
        - all
        - action
        - adventure
        - animation
        - children
        - comedy
        - crime
        - documentary
        - drama
        - family
        - fantasy
        - horror
        - mini Series
        - mystery
        - news
        - reality
        - romance
        - science-fiction
        - soap
        - special Interest
        - sport
        - suspense
        - talk Show
        - thriller
        - western
      sort-by:
        - trending
        - popularity
        - updated
        - year
        - name
        - rating
    animes:
      uris:
        - https://nyaa.si
      genres:
        - all
        - anime-music-video
        - english-translated
        - non-english-translated
        - raw
      sort-by:
        - trending
        - last added
    favorites:
      genres:
        - all
        - movies
        - tv
      sort-by:
        - watched
        - year
        - title
        - rating
  subtitle:
    url: http://api.opensubtitles.org/xml-rpc
    user-agent: Popcorn Time v1
    username: "cejoma5001@svpmail.com"
    password: "acsNFuS.!9y7X9b"
  trakt:
    url: https://api.trakt.tv
    client:
      client-id: 62a497cb224dc3d4c71a9da940fb9ef1b20ff8ab148c0ffb38b228e0a58ef246
      client-secret: 5dddda26c750b108990025e2d3a4fb4c0d348eb5c927c99622ca8edd5ca8c202
      user-authorization-uri: https://trakt.tv/oauth/authorize
      access-token-uri: https://api.trakt.tv/oauth/token
      pre-established-redirect-uri: http://localhost:9999
      token-name: oauth_token
      use-current-uri: false
