// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by protoc 29.3
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `subtitle.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:fx.ipc.proto.Subtitle)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Subtitle {
    // special fields
    // @@protoc_insertion_point(special_field:fx.ipc.proto.Subtitle.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Subtitle {
    fn default() -> &'a Subtitle {
        <Subtitle as ::protobuf::Message>::default_instance()
    }
}

impl Subtitle {
    pub fn new() -> Subtitle {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Subtitle {
    const NAME: &'static str = "Subtitle";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Subtitle {
        Subtitle::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Subtitle {
        static instance: Subtitle = Subtitle {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

/// Nested message and enums of message `Subtitle`
pub mod subtitle {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:fx.ipc.proto.Subtitle.Language)
    pub enum Language {
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.NONE)
        NONE = 0,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.CUSTOM)
        CUSTOM = 1,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.ARABIC)
        ARABIC = 2,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.BULGARIAN)
        BULGARIAN = 3,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.BOSNIAN)
        BOSNIAN = 4,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.CZECH)
        CZECH = 5,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.DANISH)
        DANISH = 6,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.GERMAN)
        GERMAN = 7,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.MODERN_GREEK)
        MODERN_GREEK = 8,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.ENGLISH)
        ENGLISH = 9,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.SPANISH)
        SPANISH = 10,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.ESTONIAN)
        ESTONIAN = 11,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.BASQUE)
        BASQUE = 12,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.PERSIAN)
        PERSIAN = 13,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.FINNISH)
        FINNISH = 14,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.FRENCH)
        FRENCH = 15,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.HEBREW)
        HEBREW = 16,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.CROATIAN)
        CROATIAN = 17,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.HUNGARIAN)
        HUNGARIAN = 18,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.INDONESIAN)
        INDONESIAN = 19,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.ITALIAN)
        ITALIAN = 20,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.LITHUANIAN)
        LITHUANIAN = 21,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.DUTCH)
        DUTCH = 22,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.NORWEGIAN)
        NORWEGIAN = 23,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.POLISH)
        POLISH = 24,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.PORTUGUESE)
        PORTUGUESE = 25,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.PORTUGUESE_BRAZIL)
        PORTUGUESE_BRAZIL = 26,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.ROMANIAN)
        ROMANIAN = 27,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.RUSSIAN)
        RUSSIAN = 28,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.SLOVENE)
        SLOVENE = 29,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.SERBIAN)
        SERBIAN = 30,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.SWEDISH)
        SWEDISH = 31,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.THAI)
        THAI = 32,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.TURKISH)
        TURKISH = 33,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.UKRAINIAN)
        UKRAINIAN = 34,
        // @@protoc_insertion_point(enum_value:fx.ipc.proto.Subtitle.Language.VIETNAMESE)
        VIETNAMESE = 35,
    }

    impl ::protobuf::Enum for Language {
        const NAME: &'static str = "Language";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Language> {
            match value {
                0 => ::std::option::Option::Some(Language::NONE),
                1 => ::std::option::Option::Some(Language::CUSTOM),
                2 => ::std::option::Option::Some(Language::ARABIC),
                3 => ::std::option::Option::Some(Language::BULGARIAN),
                4 => ::std::option::Option::Some(Language::BOSNIAN),
                5 => ::std::option::Option::Some(Language::CZECH),
                6 => ::std::option::Option::Some(Language::DANISH),
                7 => ::std::option::Option::Some(Language::GERMAN),
                8 => ::std::option::Option::Some(Language::MODERN_GREEK),
                9 => ::std::option::Option::Some(Language::ENGLISH),
                10 => ::std::option::Option::Some(Language::SPANISH),
                11 => ::std::option::Option::Some(Language::ESTONIAN),
                12 => ::std::option::Option::Some(Language::BASQUE),
                13 => ::std::option::Option::Some(Language::PERSIAN),
                14 => ::std::option::Option::Some(Language::FINNISH),
                15 => ::std::option::Option::Some(Language::FRENCH),
                16 => ::std::option::Option::Some(Language::HEBREW),
                17 => ::std::option::Option::Some(Language::CROATIAN),
                18 => ::std::option::Option::Some(Language::HUNGARIAN),
                19 => ::std::option::Option::Some(Language::INDONESIAN),
                20 => ::std::option::Option::Some(Language::ITALIAN),
                21 => ::std::option::Option::Some(Language::LITHUANIAN),
                22 => ::std::option::Option::Some(Language::DUTCH),
                23 => ::std::option::Option::Some(Language::NORWEGIAN),
                24 => ::std::option::Option::Some(Language::POLISH),
                25 => ::std::option::Option::Some(Language::PORTUGUESE),
                26 => ::std::option::Option::Some(Language::PORTUGUESE_BRAZIL),
                27 => ::std::option::Option::Some(Language::ROMANIAN),
                28 => ::std::option::Option::Some(Language::RUSSIAN),
                29 => ::std::option::Option::Some(Language::SLOVENE),
                30 => ::std::option::Option::Some(Language::SERBIAN),
                31 => ::std::option::Option::Some(Language::SWEDISH),
                32 => ::std::option::Option::Some(Language::THAI),
                33 => ::std::option::Option::Some(Language::TURKISH),
                34 => ::std::option::Option::Some(Language::UKRAINIAN),
                35 => ::std::option::Option::Some(Language::VIETNAMESE),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Language> {
            match str {
                "NONE" => ::std::option::Option::Some(Language::NONE),
                "CUSTOM" => ::std::option::Option::Some(Language::CUSTOM),
                "ARABIC" => ::std::option::Option::Some(Language::ARABIC),
                "BULGARIAN" => ::std::option::Option::Some(Language::BULGARIAN),
                "BOSNIAN" => ::std::option::Option::Some(Language::BOSNIAN),
                "CZECH" => ::std::option::Option::Some(Language::CZECH),
                "DANISH" => ::std::option::Option::Some(Language::DANISH),
                "GERMAN" => ::std::option::Option::Some(Language::GERMAN),
                "MODERN_GREEK" => ::std::option::Option::Some(Language::MODERN_GREEK),
                "ENGLISH" => ::std::option::Option::Some(Language::ENGLISH),
                "SPANISH" => ::std::option::Option::Some(Language::SPANISH),
                "ESTONIAN" => ::std::option::Option::Some(Language::ESTONIAN),
                "BASQUE" => ::std::option::Option::Some(Language::BASQUE),
                "PERSIAN" => ::std::option::Option::Some(Language::PERSIAN),
                "FINNISH" => ::std::option::Option::Some(Language::FINNISH),
                "FRENCH" => ::std::option::Option::Some(Language::FRENCH),
                "HEBREW" => ::std::option::Option::Some(Language::HEBREW),
                "CROATIAN" => ::std::option::Option::Some(Language::CROATIAN),
                "HUNGARIAN" => ::std::option::Option::Some(Language::HUNGARIAN),
                "INDONESIAN" => ::std::option::Option::Some(Language::INDONESIAN),
                "ITALIAN" => ::std::option::Option::Some(Language::ITALIAN),
                "LITHUANIAN" => ::std::option::Option::Some(Language::LITHUANIAN),
                "DUTCH" => ::std::option::Option::Some(Language::DUTCH),
                "NORWEGIAN" => ::std::option::Option::Some(Language::NORWEGIAN),
                "POLISH" => ::std::option::Option::Some(Language::POLISH),
                "PORTUGUESE" => ::std::option::Option::Some(Language::PORTUGUESE),
                "PORTUGUESE_BRAZIL" => ::std::option::Option::Some(Language::PORTUGUESE_BRAZIL),
                "ROMANIAN" => ::std::option::Option::Some(Language::ROMANIAN),
                "RUSSIAN" => ::std::option::Option::Some(Language::RUSSIAN),
                "SLOVENE" => ::std::option::Option::Some(Language::SLOVENE),
                "SERBIAN" => ::std::option::Option::Some(Language::SERBIAN),
                "SWEDISH" => ::std::option::Option::Some(Language::SWEDISH),
                "THAI" => ::std::option::Option::Some(Language::THAI),
                "TURKISH" => ::std::option::Option::Some(Language::TURKISH),
                "UKRAINIAN" => ::std::option::Option::Some(Language::UKRAINIAN),
                "VIETNAMESE" => ::std::option::Option::Some(Language::VIETNAMESE),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Language] = &[
            Language::NONE,
            Language::CUSTOM,
            Language::ARABIC,
            Language::BULGARIAN,
            Language::BOSNIAN,
            Language::CZECH,
            Language::DANISH,
            Language::GERMAN,
            Language::MODERN_GREEK,
            Language::ENGLISH,
            Language::SPANISH,
            Language::ESTONIAN,
            Language::BASQUE,
            Language::PERSIAN,
            Language::FINNISH,
            Language::FRENCH,
            Language::HEBREW,
            Language::CROATIAN,
            Language::HUNGARIAN,
            Language::INDONESIAN,
            Language::ITALIAN,
            Language::LITHUANIAN,
            Language::DUTCH,
            Language::NORWEGIAN,
            Language::POLISH,
            Language::PORTUGUESE,
            Language::PORTUGUESE_BRAZIL,
            Language::ROMANIAN,
            Language::RUSSIAN,
            Language::SLOVENE,
            Language::SERBIAN,
            Language::SWEDISH,
            Language::THAI,
            Language::TURKISH,
            Language::UKRAINIAN,
            Language::VIETNAMESE,
        ];
    }

    impl ::std::default::Default for Language {
        fn default() -> Self {
            Language::NONE
        }
    }

}
