logging:
  level:
    com.github.yoep.popcorn: WARN
    com.github.yoep.popcorn.backend: WARN

popcorn:
  loggers:
    popcorn_fx:
      level: warn
    popcorn_fx::ffi:
      level: warn
    popcorn_fx_core:
      level: warn
    popcorn_fx_core::core::loader:
      level: info
    popcorn_fx_core::core::torrents:
      level: info
    popcorn_fx_players:
      level: warn
    popcorn_fx_opensubtitles:
      level: error
    popcorn_fx_torrent:
      level: info