logging:
  level:
    com.github.yoep.player.chromecast: DEBUG
    com.github.yoep.player.qt: INFO
    com.github.yoep.popcorn.media: DEBUG
    com.github.yoep.popcorn.subtitles: DEBUG
    com.github.yoep.popcorn.ui: DEBUG
    com.github.yoep.popcorn.view: DEBUG
    com.github.yoep.popcorn: INFO
    com.github.yoep.torrent.frostwire: INFO
    com.github.yoep.torrent.stream: INFO
    com.github.yoep.video.vlc: DEBUG
    com.github.yoep.video.youtube: INFO
    com.github.yoep.video: INFO
    org.springframework: INFO

popcorn:
  update-channel: https://raw.githubusercontent.com/yoep/popcorn-fx/