logging:
  level:
    com.github.yoep.player.chromecast: INFO
    com.github.yoep.popcorn.backend.events: INFO
    com.github.yoep.popcorn.backend.media.favorites: INFO
    com.github.yoep.popcorn.backend.media.providers: INFO
    com.github.yoep.popcorn.backend.media.resume: INFO
    com.github.yoep.popcorn.backend.media.watched: INFO
    com.github.yoep.popcorn.backend.settings: INFO
    com.github.yoep.popcorn.backend.subtitles: INFO
    com.github.yoep.popcorn.backend.torrent: INFO
    com.github.yoep.popcorn.media: INFO
    com.github.yoep.popcorn.ui: INFO
    com.github.yoep.popcorn.view: INFO
    com.github.yoep.popcorn: INFO
    com.github.yoep.torrent.frostwire: INFO
    com.github.yoep.video.vlc: INFO
    com.github.yoep.video.youtube: INFO
    com.github.yoep.video: INFO
    org.springframework: INFO

popcorn:
  loggers:
    popcorn_fx:
      level: trace
    popcorn_fx::ffi::mappings::subtitle:
      level: info
    popcorn_fx_core:
      level: info
    popcorn_fx_core::core::cache:
      level: info
    popcorn_fx_core::core::config:
      level: info
    popcorn_fx_core::core::events:
      level: info
    popcorn_fx_core::core::loader:
      level: trace
    popcorn_fx_core::core::media:
      level: info
    popcorn_fx_core::core::media::favorites:
      level: info
    popcorn_fx_core::core::media::providers:
      level: info
    popcorn_fx_core::core::media::resume:
      level: info
    popcorn_fx_core::core::media::watched:
      level: info
    popcorn_fx_core::core::subtitles::parsers:
      level: info
    popcorn_fx_core::core::players:
      level: info
    popcorn_fx_core::core::playlists:
      level: info
    popcorn_fx_core::core::screen:
      level: info
    popcorn_fx_core::core::subtitles:
      level: info
    popcorn_fx_core::core::updater:
      level: info
    popcorn_fx_opensubtitles:
      level: info
    popcorn_fx_platform:
      level: info
    popcorn_fx_torrent:
      level: info
    popcorn_fx_torrent_stream:
      level: info