popcorn:
  loggers:
    jvm:
      level: info
    libfx::ipc:
      level: info
    popcorn_fx:
      level: warn
    popcorn_fx::ffi:
      level: info
    popcorn_fx_core:
      level: info
    popcorn_fx_core::core::loader:
      level: info
    popcorn_fx_core::core::media:
      level: info
    popcorn_fx_core::core::media::favorites:
      level: info
    popcorn_fx_core::core::media::providers:
      level: info
    popcorn_fx_core::core::torrents:
      level: info
    popcorn_fx_players:
      level: warn
    popcorn_fx_opensubtitles:
      level: error
    popcorn_fx_torrent:
      level: info
    popcorn_fx_torrent::torrent::dht:
      level: debug
    popcorn_fx_torrent::torrent::tracker:
      level: info
    popcorn_fx_torrent::torrent::peer::protocol:
      level: info