logging:
  level:
    com.github.yoep.player.chromecast: INFO
    com.github.yoep.popcorn.backend.media.favorites: INFO
    com.github.yoep.popcorn.backend.media.providers: INFO
    com.github.yoep.popcorn.backend.media.watched: INFO
    com.github.yoep.popcorn.backend.subtitles: DEBUG
    com.github.yoep.popcorn.media: INFO
    com.github.yoep.popcorn.ui: INFO
    com.github.yoep.popcorn.view: INFO
    com.github.yoep.popcorn: INFO
    com.github.yoep.torrent.frostwire: INFO
    com.github.yoep.torrent.stream: INFO
    com.github.yoep.video.vlc: INFO
    com.github.yoep.video.youtube: INFO
    com.github.yoep.video: INFO
    org.springframework: INFO
    com.github.yoep.torrent.stream.services: TRACE