[package]
name = "popcorn-fx-core"
version = "0.6.3"
edition = "2021"
rust-version = "1.62"
publish = false
license-file = "../LICENSE"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0"
bytes = "1.4"
chrono = "0"
derive_more = "0"
downcast-rs = "1"
futures = "0"
home = "0"
html-escape = "0"
itertools = "0"
local-ip-address = "0"
log.workspace = true
log4rs = { version = "1", features = ["console_writer"], optional = true }
mockall = "0"
percent-encoding = "2"
regex = "1"
reqwest = { version = "0", features = ["serde_json", "json", "stream"] }
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
semver = "1.0"
thiserror = "1"
tokio = { workspace = true, features = ["rt-multi-thread", "fs"] }
tokio-stream = "0"
tempfile = { version = "3", optional = true }
url = "2"
warp = "0"

[dev-dependencies]
popcorn-fx-core = { path = "../popcorn-fx-core", features = ["testing"] }

mockall = "0"
httpmock = "0"
tempfile = "3"
tokio = { workspace = true, features = ["test-util", "macros"] }

[features]
testing = ["dep:log4rs", "dep:tempfile"]
