# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master, hotfix/*, feature/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
        cache: 'maven'
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Prepare build
      run: make prerequisites
    - name: Build
      run: |
        xvfb-run make test && make build
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./application/target/site/jacoco-aggregate/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true