# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  test-java:
    name: Test Java
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'maven'
      - name: Test
        run: |
          xvfb-run -a make test-java
      - name: 'Upload Coverage'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: ./application/target/site/jacoco-aggregate/jacoco.xml
          retention-days: 2

  test-cargo:
    name: Test Cargo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "main"
          cache-on-failure: "true"
      - name: Test
        run: |
          sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config vlc
          make test-cargo
      - name: 'Upload Coverage'
        uses: actions/upload-artifact@v4
        with:
          name: lcov
          path: ./target/lcov.info
          retention-days: 2

  test-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    needs:
      - test-java
      - test-cargo

    steps:
      - uses: actions/checkout@v2
      - name: Download Java coverage
        uses: actions/download-artifact@v4
        with:
          name: jacoco
          path: ./application/target/site/jacoco-aggregate/
          merge-multiple: true
      - name: Download Cargo coverage
        uses: actions/download-artifact@v4
        with:
          name: lcov
          path: ./target/
          merge-multiple: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./application/target/site/jacoco-aggregate/jacoco.xml,./target/lcov.info
          flags: unittests
          name: codecov-umbrella
          verbose: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test-coverage

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
        cache: 'maven'
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "main"
        cache-on-failure: "true"
    - name: Build
      run: |
        sudo apt install libdbus-1-dev pkg-config
        make build