# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master, hotfix/*, feature/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo build
      run: |
        cargo install cbindgen && \
        cargo test && \
        cargo build
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache local Maven repository
      uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Prepare build
      run: mvn -B clean -Plinux
    - name: Build
      run: xvfb-run mvn -B verify -Plinux
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./application/target/site/jacoco-aggregate/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true