name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Release type'
        required: true
        default: 'minor'
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  test-java:
    name: Test Java
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 21
          cache: 'maven'
      - name: Test
        run: |
          xvfb-run -a make test-java

  test-cargo:
    name: Test Cargo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "main"
          cache-on-failure: "true"
      - name: Test
        run: |
          sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config vlc
          make test-cargo

  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    needs:
      - test-java
      - test-cargo

    steps:
    - uses: actions/checkout@v2
    - name: Release version
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@noreply.github.com'
        make bump-${{ github.event.inputs.release_type }}
        git push && git push --tags